.TH scap-workbench "8" "Sep 2013" "Red Hat" "System Administration Utilities"

.SH NAME
scap\-workbench \- GUI tool for systems compliance evaluation

.SH SYNOPSIS
\fBscap\-workbench\fR [\-\-skip\-valid] [\fIXCCDF_FILE\fR]

.SH DESCRIPTION
SCAP Workbench is GUI tool for security compliance checking. Compliance can be
described with SCAP standards - XCCDF and OVAL.

This tool enables users to:
.RS
 * evaluate local and/or remote machines using SCAP content \fB(scanning)\fR
 * perform remediation on both local and remote machines \fB(remediation)\fR
 * adjust XCCDF scanning profiles \fB(tailoring)\fR

.SH OPTIONS
.TP
\fB\-\-skip\-valid\fR
If this option is provided openscap validation will not be performed.
This is recommended only for advanced users and may cause OpenSCAP or SCAP Workbench
to crash!
.TP
\fBXCCDF_FILE\fR
If this parameter is provided the scanner will immediately open given XCCDF or
source datastream (SDS) file after it starts.

.SH SCAP CONTENT
Sample content is provided by the OpenSCAP project (in the \fBopenscap\-content\fR package).

Other sources of SCAP content are:
.TP
\fBNational Vulnerability Database\fR - \fIhttp://web.nvd.nist.gov/view/ncp/repository\fR
.TP
\fBRed Hat content repository\fR - \fIhttp://www.redhat.com/security/data/oval/\fR
.TP
\fBscap\-security\-guide project\fR - \fIhttp://fedorahosted.org/scap\-security\-guide/\fR
.TP
\fBsce\-community\-content project\fR - \fIhttp://fedorahosted.org/sce\-community\-content/\fR

.SH AUTHORS

.nf
Martin Preisler <mpreisle@redhat.com>
.fi

.SH NOTES
SCAP Workbench uses the OpenSCAP library, see \fIhttp://www.open-scap.org\fR

.SH SEE ALSO
oscap(8)
