downstream_package_name: scap-workbench
jobs:
- job: copr_build
  metadata:
    targets:
    - fedora-all-x86_64
  trigger: pull_request
- job: propose_downstream
  metadata:
    dist-git-branch: fedora-all
  trigger: release
specfile_path: scap-workbench.spec
synced_files:
- scap-workbench.spec
- .packit.yaml
upstream_package_name: scap-workbench
actions:
  post-upstream-clone: wget -N https://src.fedoraproject.org/rpms/scap-workbench/raw/master/f/scap-workbench.spec
