#!/usr/bin/env bash

# If the script fails make sure you have *epydoc* installed
# to get inheritance graphs, make sure you have *graphviz* installed

DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

rm -rf $DIR/doc
mkdir $DIR/doc
epydoc -v --html -o $DIR/doc --name "scap-workbench" --url "http://fedorahosted.org/scap-workbench" --graph all --inheritance listed \
    $DIR/src/scap_workbench

